---
# Remove dist flag once travis uses bonic as default
dist: bionic

language: perl
# Perl version matrix follows versions still in use by popular
# distributions such as Debian or Ubuntu, see:
# - https://www.cpan.org/src/
# - https://packages.debian.org/search?keywords=perl
# - https://packages.ubuntu.com/search?keywords=perl
perl:
  - 5.30
  - 5.28
  - 5.26
  - 5.24
  - 5.22
  - 5.20

cache:
  directories:
    - ~/perl_modules
before_install:
  - export MAKEFLAGS="-j $(nproc)"
  - cpanm --quiet --notest local::lib
  - eval "$(perl -Mlocal::lib=~/perl_modules)"
install:
  - cpanm --quiet --installdeps --notest .
before_script:
  - ./makeDist --nosyntaxCheck --version HEAD
  - cd ./dist/BackupPC-HEAD
  - sudo useradd -s /usr/sbin/nologin -G travis backuppc
script:
  - sudo --preserve-env=PATH,PERL5LIB ./configure.pl --batch
  - sudo --preserve-env=PATH,PERL5LIB su -m backuppc -c '/usr/local/BackupPC/bin/BackupPC -d'
  - sudo cat /var/log/BackupPC/LOG
  - >-
    sudo egrep -v '[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}(
    Reading hosts file|
    BackupPC HEAD \(Perl v5\.[0-9]{1,2}\.[0-9]\) started, pid [0-9]+|
    Next wakeup is [0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})$'
    /var/log/BackupPC/LOG; test $? -eq 1

jobs:
  - name: Lint
    language: python
    python: 3.8
    cache: pip
    before_install: skip
    install: skip
    before_script: skip
    script:
      - pip3 install pre-commit
      - pre-commit run --all --color=always --show-diff-on-failure
